alias ls='ls -F --color=auto  --group-directories-first'
alias l='ls -F --color=always  --group-directories-first'
alias la='ls -Ah --group-directories-first'
alias ll='ls -lh --group-directories-first'
alias lla='ls -lAh --group-directories-first'
alias l1='ls -1'
alias ls1='ls -1'

COMPRESSED="00;33"
DOCUMENTS="00;38;5;208"
SOURCE="00;38;5;219"
PROPS="00;38;5;139"

items=(
	"bd=40;33;01"
	"ca=30;41"
	"cd=40;33;01"
	"di=3;38;5;111"
	"do=01;35"
	"ex=00;38;5;118"
	"ln=00;38;5;51"
	"mh=00"
	"mi=01;05;37;41"
	"or=40;31;01"
	"ow=34;42"
	"pi=40;33"
	"sg=30;43"
	"so=01;35"
	"st=37;44"
	"su=37;41"
	"tw=30;42"
    "rs=0"

	"*.7z=$COMPRESSED"
	"*.Z=$COMPRESSED"
	"*.ace=$COMPRESSED"
	"*.alz=$COMPRESSED"
	"*.arc=$COMPRESSED"
	"*.arj=$COMPRESSED"
	"*.bz2=$COMPRESSED"
	"*.bz=$COMPRESSED"
	"*.cab=$COMPRESSED"
	"*.cpio=$COMPRESSED"
	"*.deb=$COMPRESSED"
	"*.dz=$COMPRESSED"
	"*.ear=$COMPRESSED"
	"*.gz=$COMPRESSED"
	"*.jar=$COMPRESSED"
	"*.lha=$COMPRESSED"
	"*.lrz=$COMPRESSED"
	"*.lz4=$COMPRESSED"
	"*.lz=$COMPRESSED"
	"*.lzh=$COMPRESSED"
	"*.lzma=$COMPRESSED"
	"*.lzo=$COMPRESSED"
	"*.rar=$COMPRESSED"
	"*.rz=$COMPRESSED"
	"*.sar=$COMPRESSED"
	"*.t7z=$COMPRESSED"
	"*.tar=$COMPRESSED"
	"*.taz=$COMPRESSED"
	"*.tbz2=$COMPRESSED"
	"*.tbz=$COMPRESSED"
	"*.tgz=$COMPRESSED"
	"*.tlz=$COMPRESSED"
	"*.txz=$COMPRESSED"
	"*.tz=$COMPRESSED"
	"*.tzo=$COMPRESSED"
	"*.war=$COMPRESSED"
	"*.xz=$COMPRESSED"
	"*.z=$COMPRESSED"
	"*.zip=$COMPRESSED"
	"*.zoo=$COMPRESSED"

	"*.md=$DOCUMENTS"

	"*.properties=$PROPS"
	"*.toml=$PROPS"
	"*.yaml=$PROPS"

	"*.c++=$SOURCE"
	"*.c=$SOURCE"
	"*.clj=$SOURCE"
	"*.cljc=$SOURCE"
	"*.cljs=$SOURCE"
	"*.cpp=$SOURCE"
	"*.cs=$SOURCE"
	"*.h=$SOURCE"
	"*.hpp=$SOURCE"
	"*.java=$SOURCE"
	"*.js=$SOURCE"
	"*.py=$SOURCE"
	"*.rs=$SOURCE"
	"*.svelte=$SOURCE"
	"*.ts=$SOURCE"
)
LS_COLORS=${(j.:.)items}
export LS_COLORS
